CREATE TABLE IF NOT EXISTS "sociallink_users" (
   "id" SERIAL PRIMARY KEY,
   "discord_id" VARCHAR(255) UNIQUE NOT NULL,
   "minecraft_token" VARCHAR(255) DEFAULT NULL,
   "minecraft_uuid" VARCHAR(255) DEFAULT NULL,
   "email" VARCHAR(255) DEFAULT NULL,
   "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
